name: t
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  go_router: ^13.0.0
  flutter_mobx: ^2.0.2

  path: ^1.8.0
  path_provider: ^2.0.3

  qr_flutter:
    git:
      url: https://github.com/hhanh00/qr.flutter.git
      ref: 4bdb1126e553b474b80c8c91e9f9e43baf1e9c4e

  http: ^1.1.2
  intl: ^0.18.0
  easy_debounce: ^2.0.3

  gap: ^3.0.1
  font_awesome_flutter: ^10.5.0
  material_design_icons_flutter: ^7.0.7296
  rflutter_alert: ^2.0.7
  velocity_x: ^4.1.2

  tuple: ^2.0.1
  timeago: ^3.5.0
  decimal: ^2.1.0
  key_guardmanager: ^1.0.0

  shared_preferences: ^2.0.7
  window_manager: ^0.3.0

  mustache_template: ^2.0.0
  flutter_markdown: ^0.6.6
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flex_color_scheme: ^7.3.1
  flutter_palette: ^1.1.0+1
  another_flushbar: ^1.12.30

  bubble: ^1.2.1
  graphic: ^2.2.1
  im_stepper: ^1.0.1
  loading_animation_widget: ^1.2.0
  settings_ui: ^2.0.2

  get_it: ^7.6.4
  rxdart: ^0.27.7

  share_plus: ^7.2.1
  file_picker: ^6.1.1
  cross_file: ^0.3.3

  # flutter_zxing:
  #   path: flutter_zxing
  sensors_plus: ^4.0.0
  connectivity_plus: ^5.0.2

  local_auth: ^2.1.2                       # has custom setup
  app_links: ^3.4.1                        # has custom setup
  url_launcher: ^6.0.10                    # has custom setup
  #url_protocol: ^1.0.0
  quick_actions: ^1.0.6

  csv: ^5.0.0
  badges: ^3.1.2

  network_info_plus : ^4.1.0

  flutter_localizations:
    sdk: flutter
  flutter_foreground_task: ^6.1.2
  awesome_notifications: ^0.8.1

  getwidget: ^4.0.0
  reflectable: ^4.0.5

  cupertino_icons: ^1.0.2

  warp_api:
    path: warp_api

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
