name: "Build Windows app"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-bin:
    runs-on: windows-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build vars
        shell: bash
        run: |
          cat build.env >> $GITHUB_ENV
      - name: Download params
        shell: bash
        env: 
          TEMP: ${{ runner.temp }}
        run: |
          mkdir -p $TEMP/.zcash-params
          curl https://download.z.cash/downloads/sapling-output.params --output $TEMP/.zcash-params/sapling-output.params
          curl https://download.z.cash/downloads/sapling-spend.params --output $TEMP/.zcash-params/sapling-spend.params
          cp $TEMP/.zcash-params/* assets/
      - name: Build Rust
        env: 
          HOME: ${{ runner.temp }}
        run: |
          cargo b -r --features=dart_ffi,sqlcipher,ledger
      - name: Build Flutter
        shell: bash
        run: |
          pushd $HOME
          git clone --branch $FLUTTER_VERSION --depth 1 https://github.com/flutter/flutter.git
          export PATH=$PATH:$HOME/flutter/bin
          popd
          flutter pub get
          flutter pub run build_runner build -d
          (cd warp_api; flutter pub get)
          flutter build windows
      - name: Package
        shell: bash
        run: |
          export PATH=$PATH:$HOME/flutter/bin
          cp target/release/warp_api_ffi.dll build/windows/x64/runner/release
          pushd build/windows/x64/runner
          mv Release ywallet
          7z a ../../../../ywallet.zip ywallet
          popd
          flutter pub run msix:create
          mv build/windows/x64/runner/Release/YWallet.msix .
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: YWallet.zip
          path: ywallet.zip
          retention-days: 3
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ywallet.zip

