name: "Build iOS app"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build vars
        run: |
          cat build.env >> $GITHUB_ENV

      - name: Build Rust
        run: |
          mkdir -p $HOME/.zcash-params
          curl https://download.z.cash/downloads/sapling-output.params --output $HOME/.zcash-params/sapling-output.params
          curl https://download.z.cash/downloads/sapling-spend.params --output $HOME/.zcash-params/sapling-spend.params
          rustup target add aarch64-apple-ios
          cargo install cargo-lipo
          sed -e 's/cdylib/staticlib/' < zcash-sync/Cargo.toml >/tmp/out.toml
          mv /tmp/out.toml zcash-sync/Cargo.toml
          cargo lipo --release --features=dart_ffi --targets=aarch64-apple-ios
          mv target/aarch64-apple-ios/release/libwarp_api_ffi.a warp_api/ios
          cp zcash-sync/binding.h warp_api/ios/Classes

      - name: Install the Apple certificate and provisioning profile
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          security create-keychain -p R5qx5GGokNBm $HOME/build.keychain
          security unlock-keychain -p R5qx5GGokNBm $HOME/build.keychain
          security import ./ios/certs/Certificates.p12 -P $KEY_PASSWORD -A -t cert -f pkcs12 -k $HOME/build.keychain
          security list-keychain -d user -s $HOME/build.keychain
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp ./ios/certs/YWallet_AppStore.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles"
          pushd $HOME
          git clone --branch $FLUTTER_VERSION --depth 1 https://github.com/flutter/flutter.git
          export PATH=$PATH:$HOME/flutter/bin
          popd
          flutter pub get
          (cd warp_api; flutter pub get)
          flutter build ipa

      # - name: Upload application
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app
      #     path: ./build/ios/archive/Runner.xcarchive
      #     retention-days: 3

